stages:
  - build
  - test

threads: 4

build_example:
  stage: build
  image: ghcr.io/rikorose/gcc-cmake:latest
  artifacts: ["build/"]
  variables:
    - FLAG: "-DCMAKE_BUILD_TYPE=Release"
  script:
    - cmake -S . -B build $FLAG
    - cmake --build build

debug_example:
  stage: build
  image: ghcr.io/rikorose/gcc-cmake:latest
  artifacts: ["build-debug/"]
  variables:
    - FLAG: "-DCMAKE_BUILD_TYPE=Debug"
  script:
    - cmake -S . -B build-debug $FLAG
    - cmake --build build-debug

test_release:
  stage: test
  image: ghcr.io/rikorose/gcc-cmake:latest
  script:
    - mkdir -p build
    - cp -r artifacts/build_example/build/build/* build/
    - ctest --test-dir build --output-on-failure

test_debug:
  stage: test
  image: ghcr.io/rikorose/gcc-cmake:latest
  script:
    - mkdir -p build-debug
    - cp -r artifacts/debug_example/build-debug/build-debug/* build-debug/
    - ctest --test-dir build-debug --output-on-failure
