stages:
  - test
  - build

threads: 4

unit_tests:
  stage: test
  image: golang:1.26
  script:
    - go mod download
    - go vet ./...
    - go test -v ./...
    - go test -bench="." -benchmem -run=^$ ./...

build_app:
  stage: build
  image: golang:1.26
  artifacts: ["velkor"]
  script:
    - go build -ldflags="-s -w" -o velkor  ./exe
