name: Go CI/CD
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum
      - name: Download dependencies
        run: go mod download
      - name: Run vet
        run: go vet ./...
      - name: Run tests
        run: go test -v ./...
      - name: Run benchmarks
        run: go test -bench="." -benchmem -run=^$ ./...
  build:
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary: velkor
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary: velkor.exe
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          go build -ldflags="-s -w" -o dist/${{ matrix.binary }} ./exe

      - name: Build RPM and DEB packages
        if: matrix.goos == 'linux'
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

          VERSION="${GITHUB_REF_NAME#v}"
          if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
            VERSION="0.0.1"
          fi

          cat <<EOF > nfpm.yaml
name: "velkor"
arch: "amd64"
platform: "linux"
version: "${VERSION}"
section: "utils"
priority: "optional"
maintainer: "Michał Skoczylas"
description: "Velkor CLI tool"
homepage: "https://github.com/${{ github.repository }}"
license: "BSD-2-Clause"
contents:
  - src: dist/velkor
    dst: /usr/bin/velkor
EOF

          nfpm package --config nfpm.yaml --target dist/velkor.deb
          nfpm package --config nfpm.yaml --target dist/velkor.rpm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}
          path: src/dist/
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/linux/*
            artifacts/windows/*
